all:
	gcc smart.c -o smart -Wall -Wno-unused-function -pthread

clean:
	rm -f smart

install:
	cp ../ardubot.conf /etc/ardubot.conf

uninstall:
	rm -f /etc/ardubot.conf
#PROG = webserver
#include examples.mk
